### PR TITLE
update install rjags package

### PR DESCRIPTION
**Pull request by johntilelli**
in order for this install to work I had to wrap rjags in quotes

### CODE REVIEW

**Comment by johntilelli** [comment]
it looks like I'm still having issues with rjags - it's holding up installation of BayesianFirstAid. Getting this error:
Error : .onLoad failed in loadNamespace() for 'rjags', details:
  call: dyn.load(file, DLLpath = DLLpath, ...)
  error: unable to load shared object

**Comment by Rmadillo** [comment]
What platform are you on and which versions of JAGS, rjags, and BFA are you using?

On Aug 10, 2016, at 1:33 AM, johntilelli <notifications@github.com<mailto:notifications@github.com>> wrote:

it looks like I'm still having issues with rjags - it's holding up installation of BayesianFirstAid. Getting this error:
Error : .onLoad failed in loadNamespace() for 'rjags', details:
call: dyn.load(file, DLLpath = DLLpath, ...)
error: unable to load shared object

##

**Comment by johntilelli** [comment]
The error was due to my version of R - I think everything is okay here.

**Comment by Rmadillo** [comment]
Sounds good!

**Pull request closed without merging**
